# File: exercises/security/secret-management/azure-key-vault-secretstore.yaml
# Description: ClusterSecretStore for Azure Key Vault integration
# Tutorial Reference: docs/security/02-secret-management.md
# Prerequisites: External Secrets Operator installed, Azure Key Vault configured

apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: azure-key-vault
  labels:
    app: external-secrets
    component: azure-key-vault
spec:
  provider:
    azurekv:
      vaultUrl: "https://your-key-vault.vault.azure.net/"
      authType: ServicePrincipal
      servicePrincipal:
        secretRef:
          clientId:
            name: azure-secret
            key: clientId
            namespace: external-secrets-system
          clientSecret:
            name: azure-secret
            key: clientSecret
            namespace: external-secrets-system
        tenantId: "your-tenant-id"
