# File: exercises/security/secret-management/external-secret-example.yaml
# Description: Example ExternalSecret to fetch database credentials from Azure Key Vault
# Tutorial Reference: docs/security/02-secret-management.md
# Prerequisites: ClusterSecretStore configured, secret exists in Azure Key Vault

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: database-credentials
  namespace: default
  labels:
    app: my-app
    component: database
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: azure-key-vault
    kind: ClusterSecretStore
  target:
    name: my-app-db-credentials
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        DB_HOST: "{{ .host }}"
        DB_USERNAME: "{{ .username }}"
        DB_PASSWORD: "{{ .password }}"
        DB_NAME: "{{ .database }}"
        CONNECTION_STRING: "host={{ .host }} user={{ .username }} password={{ .password }} dbname={{ .database }} sslmode=require"
  data:
  - secretKey: "host"
    remoteRef:
      key: "my-app-db-host"
  - secretKey: "username"
    remoteRef:
      key: "my-app-db-username"
  - secretKey: "password"
    remoteRef:
      key: "my-app-db-password"
  - secretKey: "database"
    remoteRef:
      key: "my-app-db-name"
