# File: exercises/security/secret-management/external-secrets-installation.yaml
# Description: ArgoCD Application to install External Secrets Operator
# Tutorial Reference: docs/security/02-secret-management.md
# Prerequisites: ArgoCD installed

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.external-secrets.io
    targetRevision: 0.9.9
    chart: external-secrets
    helm:
      values: |
        installCRDs: true
        replicaCount: 2
        serviceMonitor:
          enabled: true
        certController:
          serviceMonitor:
            enabled: true
        webhook:
          serviceMonitor:
            enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
