# File: exercises/gitops-fundamentals/rbac/argocd-crossplane-clusterrole.yaml
# Description: ClusterRole granting ArgoCD permissions to manage Crossplane resources
# Tutorial Reference: docs/gitops-fundamentals/01-argocd-setup.md
# Prerequisites: ArgoCD installed

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-crossplane-manager-role
rules:
- apiGroups:
  - apiextensions.crossplane.io
  resources:
  - compositions
  - compositeresourcedefinitions
  verbs:
  - "*"
- apiGroups:
  - pkg.crossplane.io
  resources:
  - providers
  - configurations
  - functions
  verbs:
  - "*"
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - watch
---
# File: exercises/gitops-fundamentals/rbac/argocd-crossplane-clusterrole.yaml
# Description: ClusterRoleBinding associating ArgoCD controller with Crossplane permissions
# Tutorial Reference: docs/gitops-fundamentals/01-argocd-setup.md
# Prerequisites: ArgoCD installed and ClusterRole created

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-crossplane-manager-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argocd-crossplane-manager-role
subjects:
- kind: ServiceAccount
  name: argocd-application-controller
  namespace: argocd
